name: Aggiornamento Automatico Chiusura BTP

on:
  schedule:
    - cron: '53 16 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout repository corrente
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installa dipendenze
      - name: Installa dipendenze
        run: |
          pip install pandas requests

      # 4. Esegue lo script
      - name: Esegui script di aggiornamento prezzi
        run: python update_bonds.py

      # 5. Verifica output
      - name: Controlla file prodotti
        run: |
          echo "=== ISIN CONFIGURATI ==="
          cat isins.txt

          echo ""
          echo "=== FILE GENERATI ==="
          ls -la output

      # 6. Clona la repo di destinazione
      - name: Clona portfolio-streamlit
        env:
          API_TOKEN_GITHUB: ${{ secrets.PORTFOLIO_TOKEN }}
        run: |
          git clone https://x-access-token:${API_TOKEN_GITHUB}@github.com/MarioPEL58/portfolio-streamlit.git

      # 7. Copia tutti i CSV presenti in isins.txt
      - name: Aggiorna file CSV
        run: |
          while read isin
          do
            [ -z "$isin" ] && continue
      
            if [ -f "output/${isin}.csv" ]; then
      
              echo "Copio output/${isin}.csv"
      
              cp "output/${isin}.csv" \
                 "portfolio-streamlit/data/bonds/${isin}.csv"
      
            else
      
              echo "ATTENZIONE: output/${isin}.csv non trovato"
      
            fi
      
          done < isins.txt

      # 8. Commit e push
      - name: Commit e Push
        env:
          API_TOKEN_GITHUB: ${{ secrets.PORTFOLIO_TOKEN }}
        run: |
          cd portfolio-streamlit

          git config user.email "actions@github.com"
          git config user.name "BTP-Data-Bot"

          git add data/bonds/*.csv

          git commit -m "Aggiornamento automatico BTP [skip ci]" || echo "Nessuna modifica da committare"

          git status

          git push origin dev
