name: Update Ticker Data

on:
  schedule:
    - cron: '0 0 * * 2-6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install yfinance pandas requests

    - name: Run download script
      run: python download_data.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add data/
        git commit -m "Aggiornamento dati: $(date +'%Y-%m-%d')" || echo "Nessuna modifica"
        git push
